// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type SendEmailRequest struct {
	Email   string `json:"email"`
	Title   string `json:"title"`
	Content string `json:"content"`
	IsDelay bool   `json:"is_delay,default=false"` // 是否延迟发送
	Time    int64  `json:"time,optional"`          // 延迟发送时间,10位时间戳
}

type SendEmailResponse struct {
}
