// Code generated by goctl. DO NOT EDIT!
// Source: asynqserver.proto

package server

import (
	"context"

	"gozero-asynq/asynqserver/asynqserver"
	"gozero-asynq/asynqserver/internal/logic"
	"gozero-asynq/asynqserver/internal/svc"
)

type AsynqserverServer struct {
	svcCtx *svc.ServiceContext
	asynqserver.UnimplementedAsynqserverServer
}

func NewAsynqserverServer(svcCtx *svc.ServiceContext) *AsynqserverServer {
	return &AsynqserverServer{
		svcCtx: svcCtx,
	}
}

func (s *AsynqserverServer) Ping(ctx context.Context, in *asynqserver.Request) (*asynqserver.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
