// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: asynqserver.proto

package asynqserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AsynqserverClient is the client API for Asynqserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsynqserverClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type asynqserverClient struct {
	cc grpc.ClientConnInterface
}

func NewAsynqserverClient(cc grpc.ClientConnInterface) AsynqserverClient {
	return &asynqserverClient{cc}
}

func (c *asynqserverClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/asynqserver.Asynqserver/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsynqserverServer is the server API for Asynqserver service.
// All implementations must embed UnimplementedAsynqserverServer
// for forward compatibility
type AsynqserverServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAsynqserverServer()
}

// UnimplementedAsynqserverServer must be embedded to have forward compatible implementations.
type UnimplementedAsynqserverServer struct {
}

func (UnimplementedAsynqserverServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAsynqserverServer) mustEmbedUnimplementedAsynqserverServer() {}

// UnsafeAsynqserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsynqserverServer will
// result in compilation errors.
type UnsafeAsynqserverServer interface {
	mustEmbedUnimplementedAsynqserverServer()
}

func RegisterAsynqserverServer(s grpc.ServiceRegistrar, srv AsynqserverServer) {
	s.RegisterService(&Asynqserver_ServiceDesc, srv)
}

func _Asynqserver_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsynqserverServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asynqserver.Asynqserver/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsynqserverServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Asynqserver_ServiceDesc is the grpc.ServiceDesc for Asynqserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Asynqserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asynqserver.Asynqserver",
	HandlerType: (*AsynqserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Asynqserver_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "asynqserver.proto",
}
